from __future__ import annotations

from contextlib import redirect_stdout
from io import StringIO
from typing import Any, Dict, Optional
import traceback
import pandas as pd

from core.ads_types import ExecutionCell, ExecutionStep
from engines.visualization_engine import auto_select_visualizations
from engines.ml_experiment_engine import run_experiments
from llm.model_router import query_llm


SAFE_BUILTINS = {
    "len": len,
    "min": min,
    "max": max,
    "sum": sum,
    "range": range,
    "print": print,
    "str": str,
    "float": float,
    "int": int,
    "list": list,
    "dict": dict,
}


def _build_code_for_step(step: ExecutionStep) -> str:
    if step.tool == "eda":
        return (
            "profile = {\n"
            "  'rows': len(df),\n"
            "  'columns': list(df.columns),\n"
            "  'null_counts': df.isnull().sum().to_dict(),\n"
            "  'dtypes': {c: str(t) for c, t in df.dtypes.items()}\n"
            "}\n"
            "print('Profile generated for', len(df), 'rows')\n"
        )
    if step.tool == "feature_engineering":
        return (
            "for col in df.columns:\n"
            "  if str(df[col].dtype) == 'object':\n"
            "    df[col] = df[col].fillna('Unknown')\n"
            "  else:\n"
            "    df[col] = df[col].fillna(df[col].median())\n"
            "print('Feature engineering completed')\n"
        )
    if step.tool == "insight_generation":
        return "print('Insights will be generated by insight layer')\n"
    return f"print('Executing step: {step.title}')\n"


def execute_step(
    step: ExecutionStep,
    df: pd.DataFrame,
    sql_context: Optional[Dict[str, str]] = None,
) -> ExecutionCell:
    cell = ExecutionCell(
        cell_id=f"cell_{step.step_id}",
        step_id=step.step_id,
        title=step.title,
        code=_build_code_for_step(step),
        status="running",
    )
    try:
        if step.tool == "visualization":
            charts = auto_select_visualizations(df)
            cell.artifacts["charts"] = charts
            cell.logs.append(f"Generated {len(charts)} chart artifacts.")
            cell.status = "success"
            return cell

        if step.tool == "ml_experiment":
            target_col = df.columns[-1]
            cell.artifacts["ml_experiments"] = run_experiments(df, target_col=target_col)
            cell.logs.append(f"Ran ML experiments with target: {target_col}")
            cell.status = "success"
            return cell

        if step.tool == "sql":
            if not sql_context:
                raise ValueError("SQL context is missing.")
            from engines.sql_engine import nl_to_sql, execute_sql_plan

            sql_text = nl_to_sql(sql_context["prompt"], sql_context["schema"])
            sql_result = execute_sql_plan(sql_context["connection_string"], sql_text)
            sql_df = sql_result.pop("dataframe")
            cell.artifacts["sql"] = {"sql_text": sql_text, "result": sql_result}
            cell.logs.append(f"SQL execution returned {len(sql_df)} rows.")
            cell.status = "success"
            return cell

        # Python cell execution (jupyter-style code cell)
        stdout = StringIO()
        globals_dict: Dict[str, Any] = {"__builtins__": SAFE_BUILTINS}
        locals_dict: Dict[str, Any] = {"df": df.copy(), "pd": pd}

        with redirect_stdout(stdout):
            exec(cell.code, globals_dict, locals_dict)

        cell.stdout = stdout.getvalue()
        if "profile" in locals_dict:
            cell.artifacts["profile"] = locals_dict["profile"]
        if "df" in locals_dict and isinstance(locals_dict["df"], pd.DataFrame):
            cell.artifacts["data_preview"] = (
                locals_dict["df"].head(10).fillna("").to_dict(orient="records")
            )
        cell.status = "success"
        return cell
    except Exception as exc:
        cell.status = "error"
        cell.error = str(exc)
        cell.logs.append(traceback.format_exc())
        return cell


def generate_insight_narration(goal: str, cells: list[ExecutionCell]) -> str:
    compact = []
    for cell in cells:
        compact.append(
            {
                "title": cell.title,
                "status": cell.status,
                "artifacts": list(cell.artifacts.keys()),
                "stdout": cell.stdout[:500],
            }
        )

    try:
        response = query_llm(
            "You are a senior data scientist. Provide concise insights as bullet points.",
            f"Goal: {goal}\nExecution summary: {compact}",
        )
        return response.strip()
    except Exception:
        return "Insights generated. Key drivers likely include feature interactions and data quality improvements."
